import sys
sys.path.insert(0, __import__('os').path.dirname(__import__('os').path.abspath(__file__)))
from shapes import FRONT, BACK, expand

def kind_swift(kind):
    if kind == 'base': return '.base'
    if kind == 'body': return '.body'
    return f'.muscle(.{kind})'

def parts(shapes):
    lines = []
    for kind, pts in expand(shapes):
        coords = ', '.join(f'{x:g}, {y:g}' for x, y in pts)
        lines.append(f'        Part({kind_swift(kind)}, [{coords}]),')
    return '\n'.join(lines)

print(f'''import CoreGraphics

// Generated by tools/musclemap/gen_swift.py from tools/musclemap/shapes.py — edit the shapes there, then run\n// `python3 tools/musclemap/gen_swift.py > ForgeFit/Views/Components/MuscleMapGeometry.swift`.\n// `python3 tools/musclemap/render.py` writes a preview image.
// Coordinates are on a 100 x 200 canvas per view (x 0–100, y 0–200), mirrored left/right.

/// The shapes that make up the front and back body in `MuscleMapView`.
enum MuscleMapGeometry {{
    enum Kind: Equatable {{
        /// The body silhouette, drawn first so the gaps between muscles read as definition lines.
        case base
        /// Head, neck, hands and feet.
        case body
        case muscle(MuscleGroup)
    }}

    struct Part {{
        let kind: Kind
        let points: [CGPoint]

        init(_ kind: Kind, _ xy: [CGFloat]) {{
            self.kind = kind
            points = stride(from: 0, to: xy.count - 1, by: 2).map {{ CGPoint(x: xy[$0], y: xy[$0 + 1]) }}
        }}
    }}

    static let front: [Part] = [
{parts(FRONT)}
    ]

    static let back: [Part] = [
{parts(BACK)}
    ]
}}''')
