import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from geometry import build

def kind_swift(kind):
    if kind in ('base', 'other'): return f'.{kind}'
    return f'.muscle(.{kind})'

def parts(view):
    lines = []
    for kind, pts in view:
        coords = ', '.join(f'{x:g}, {y:g}' for x, y in pts)
        lines.append(f'        Part({kind_swift(kind)}, [{coords}]),')
    return '\n'.join(lines)

views = build()

print(f'''import CoreGraphics

// Generated by tools/musclemap/gen_swift.py from tools/musclemap/shapes.py and geometry.py — edit
// the shapes there, then run (needs `pip install numpy scipy scikit-image shapely pillow`)
// `python3 tools/musclemap/gen_swift.py > ForgeFit/Views/Components/MuscleMapGeometry.swift`.
// `python3 tools/musclemap/render.py preview.png` writes a preview image.
// Coordinates are on a 100 x 200 canvas per view (x 0–100, y 0–200). Each part is a closed outline.

/// The shapes that make up the front and back body in `MuscleMapView`.
enum MuscleMapGeometry {{
    enum Kind: Equatable {{
        /// The body silhouette, drawn first so the gaps between muscles read as definition lines.
        case base
        /// A muscle no exercise group trains (hip, inner thigh, shin); always drawn dim.
        case other
        case muscle(MuscleGroup)
    }}

    struct Part {{
        let kind: Kind
        let points: [CGPoint]

        init(_ kind: Kind, _ xy: [CGFloat]) {{
            self.kind = kind
            points = stride(from: 0, to: xy.count - 1, by: 2).map {{ CGPoint(x: xy[$0], y: xy[$0 + 1]) }}
        }}
    }}

    static let front: [Part] = [
{parts(views['front'])}
    ]

    static let back: [Part] = [
{parts(views['back'])}
    ]
}}''')
