import SwiftUI

/// An anatomy-chart body, front and/or back, with the trained muscles highlighted: primary muscles
/// in the accent, supporting muscles muted. Used on plan, day and exercise cards. The shapes come from
/// `MuscleMapGeometry` (generated by tools/musclemap).
struct MuscleMapView: View {
    enum Sides { case front, back, both, auto }
    enum Region { case full, upper, lower, auto }
    /// `onDark` for the dark cards; `onAccent` draws in ink for the lime hero card.
    enum Style { case onDark, onAccent }

    var primary: Set<MuscleGroup>
    var secondary: Set<MuscleGroup> = []
    var sides: Sides = .both
    var region: Region = .full
    var style: Style = .onDark

    var body: some View {
        let lit = Self.drawn(primary)
        let supporting = Self.drawn(secondary).subtracting(lit)
        let views = resolvedSides(lit: lit)
        let shown = resolvedRegion(lit: lit.isEmpty ? supporting : lit)
        let box = viewBox(shown)
        let fade = fadeEdge(shown, box)
        let colors = palette
        Canvas { context, size in
            let gap: CGFloat = 6
            let totalWidth = box.width * CGFloat(views.count) + gap * CGFloat(views.count - 1)
            let scale = min(size.width / totalWidth, size.height / box.height)
            let originX = (size.width - totalWidth * scale) / 2
            let originY = (size.height - box.height * scale) / 2

            for (index, outlines) in views.enumerated() {
                var transform = CGAffineTransform(translationX: originX + CGFloat(index) * (box.width + gap) * scale,
                                                  y: originY)
                transform = transform.scaledBy(x: scale, y: scale).translatedBy(x: -box.minX, y: -box.minY)

                context.drawLayer { layer in
                    // A half-body view is cut at the waist; keep the rest of the figure out of it.
                    layer.clip(to: Path(box.applying(transform)))
                    for outline in outlines {
                        let color: Color
                        switch outline.kind {
                        case .base: color = colors.base
                        case .other: color = colors.muscle
                        case .muscle(let group):
                            if lit.contains(group) {
                                color = colors.primary
                            } else if supporting.contains(group) {
                                color = colors.secondary
                            } else {
                                color = colors.muscle
                            }
                        }
                        layer.fill(outline.path.applying(transform), with: .color(color))
                    }
                    // Fade the cut edge out rather than ending the body on a hard line.
                    if let fade {
                        layer.blendMode = .destinationOut
                        layer.fill(Path(fade.rect.applying(transform)),
                                   with: .linearGradient(Gradient(colors: [.clear, .black]),
                                                         startPoint: fade.from.applying(transform),
                                                         endPoint: fade.to.applying(transform)))
                    }
                }
            }
        }
        .accessibilityHidden(true)
    }

    private var palette: (base: Color, muscle: Color, secondary: Color, primary: Color) {
        switch style {
        case .onDark:
            return (Color(white: 0.17), Color(white: 0.29), Theme.voltDeep, Theme.volt)
        case .onAccent:
            return (Theme.ink.opacity(0.14), Theme.ink.opacity(0.34), Theme.ink.opacity(0.6), Theme.ink)
        }
    }

    // MARK: Layout

    private func resolvedSides(lit: Set<MuscleGroup>) -> [[Outline]] {
        switch sides {
        case .front: return [Self.front]
        case .back: return [Self.back]
        case .both: return [Self.front, Self.back]
        case .auto:
            let backOnly: Set<MuscleGroup> = [.back, .triceps, .hamstrings, .glutes]
            let frontOnly: Set<MuscleGroup> = [.chest, .biceps, .core, .quads]
            let showsBack = !lit.isDisjoint(with: backOnly) && lit.isDisjoint(with: frontOnly)
            return [showsBack ? Self.back : Self.front]
        }
    }

    private func resolvedRegion(lit: Set<MuscleGroup>) -> Region {
        guard region == .auto else { return region }
        let upper: Set<MuscleGroup> = [.chest, .back, .shoulders, .biceps, .triceps, .forearms, .core]
        let lower: Set<MuscleGroup> = [.quads, .hamstrings, .glutes, .calves]
        if !lit.isEmpty && lit.isSubset(of: upper) { return .upper }
        if !lit.isEmpty && lit.isSubset(of: lower) { return .lower }
        return .full
    }

    /// The part of the 100 x 200 figure to show. The upper body stops at the hips, the lower body
    /// starts at the waist.
    private func viewBox(_ region: Region) -> CGRect {
        switch region {
        case .upper: return CGRect(x: 5, y: 3, width: 90, height: 101)
        case .lower: return CGRect(x: 28, y: 80, width: 44, height: 114)
        case .full, .auto: return CGRect(x: 5, y: 3, width: 90, height: 191)
        }
    }

    /// The band along the cut edge of a half-body view that fades out, from fully kept to gone.
    private func fadeEdge(_ region: Region, _ box: CGRect) -> (rect: CGRect, from: CGPoint, to: CGPoint)? {
        let depth: CGFloat = 8
        switch region {
        case .upper:
            let rect = CGRect(x: box.minX, y: box.maxY - depth, width: box.width, height: depth)
            return (rect, CGPoint(x: rect.midX, y: rect.minY), CGPoint(x: rect.midX, y: rect.maxY))
        case .lower:
            let rect = CGRect(x: box.minX, y: box.minY, width: box.width, height: depth)
            return (rect, CGPoint(x: rect.midX, y: rect.maxY), CGPoint(x: rect.midX, y: rect.minY))
        case .full, .auto:
            return nil
        }
    }

    // MARK: Muscles

    /// The muscle regions a group lights up. Full body and cardio light the big movers.
    static func drawn(_ groups: Set<MuscleGroup>) -> Set<MuscleGroup> {
        var result = Set<MuscleGroup>()
        for group in groups {
            switch group {
            case .fullBody:
                result.formUnion([.chest, .back, .shoulders, .quads, .glutes, .hamstrings, .core])
            case .cardio:
                result.formUnion([.quads, .hamstrings, .glutes, .calves])
            default:
                result.insert(group)
            }
        }
        return result
    }

    /// One shape of the figure, as a path in figure coordinates, built once.
    struct Outline {
        let kind: MuscleMapGeometry.Kind
        let path: Path

        init(_ part: MuscleMapGeometry.Part) {
            kind = part.kind
            var path = Path()
            path.addLines(part.points)
            path.closeSubpath()
            self.path = path
        }
    }

    static let front = MuscleMapGeometry.front.map(Outline.init)
    static let back = MuscleMapGeometry.back.map(Outline.init)
}

extension MuscleMapView {
    /// The muscles a single exercise works.
    init(exercise: Exercise, sides: Sides = .auto, region: Region = .auto) {
        self.init(primary: [exercise.primary], secondary: Set(exercise.secondary), sides: sides, region: region)
    }

    /// The muscles a set of planned exercises works: the most-trained groups lit fully.
    init(exercises: [PlannedExercise], sides: Sides = .both, style: Style = .onDark) {
        var counts: [MuscleGroup: Int] = [:]
        var supporting = Set<MuscleGroup>()
        for item in exercises {
            guard let exercise = item.exercise else { continue }
            counts[exercise.primary, default: 0] += item.sets
            supporting.formUnion(exercise.secondary)
        }
        let top = counts.values.max() ?? 0
        // Groups with at least a third of the busiest group's sets count as main targets.
        let primary = Set(counts.filter { top > 0 && Double($0.value) >= Double(top) / 3 }.keys)
        self.init(primary: primary, secondary: supporting.union(counts.keys), sides: sides, region: .full, style: style)
    }
}

/// A small rounded tile with the muscle map of one exercise, for list rows.
struct MuscleBadge: View {
    let exercise: Exercise
    var size: CGFloat = 40

    var body: some View {
        MuscleMapView(exercise: exercise)
            .padding(size * 0.08)
            .frame(width: size, height: size)
            .background(RoundedRectangle(cornerRadius: size * 0.3, style: .continuous).fill(Color(white: 0.09)))
    }
}
